[package]
name = "sortfish"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vampirc-uci = { version = "0.11.1", features = ["chess"] }
chess = "3.2.0"